### ISSUE TITLE
[PE-D] The explanation for "export" command missing important info

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-T12-2/tp#146]
![image.png](https://raw.githubusercontent.com/DesmondTo/ped/main/files/ccc4d340-4420-47f4-a63f-586d3c378ce6.png)
This section does not tell the user where is the target location of the exported file. The user need to search through the folder in order to find it. I think it is important to include the file path :)

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: DesmondTo/ped#11

**Comment by marcuschj** [comment]
I will add the screenshot of the exported file, don't close the issue pls
